name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: jdx/mise-action@v2
        with:
          experimental: true
  
      - run: bun install --no-cache
          
      # Important: use the custom launch template name
      - run: bunx nx start-ci-run --distribute-on="3 linux-bun" --stop-agents-after="e2e-ci"

      # Prepend any command with "nx record --" to record its logs to Nx Cloud
      - run: bunx  nx record -- npx nx format:check  --base="remotes/origin/main"
      - run: bunx  nx run-many -t lint test build typecheck e2e-ci
      # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
      - run: bunx nx fix-ci
        if: always()
